name: Github workflow
on: workflow_dispatch # This workflow can be manually triggered
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Good bye"
        




